# Generated by Django 4.1.7 on 2023-03-11 04:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='object_id',
            field=models.UUIDField(default=uuid.UUID('897816dc-2636-49ee-8c86-0329245837c3')),
        ),
    ]
