# Generated by Django 4.1.7 on 2023-03-12 00:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contact_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='object_id',
            field=models.UUIDField(default=uuid.UUID('a5458f44-e005-4415-9e69-a69aab53e2ec')),
        ),
    ]
