# Generated by Django 4.1.7 on 2023-03-12 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contact_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='object_id',
            field=models.UUIDField(default=uuid.UUID('11eb72d1-e396-4535-b4d1-18421dc2033a')),
        ),
    ]
